# Generated by Django 2.0.1 on 2018-01-17 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_auto_20180105_1859'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='config',
            options={'verbose_name': '系统配置', 'verbose_name_plural': '系统配置'},
        ),
        migrations.AddField(
            model_name='exam',
            name='lock',
            field=models.BooleanField(default=False, verbose_name='关闭'),
        ),
        migrations.AlterField(
            model_name='config',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='config',
            name='key',
            field=models.CharField(max_length=128, unique=True, verbose_name='键'),
        ),
        migrations.AlterField(
            model_name='config',
            name='value',
            field=models.TextField(verbose_name='值'),
        ),
        migrations.AlterField(
            model_name='teacherexam',
            name='schoolexam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.Schoolexam', verbose_name='在某学校的考试'),
        ),
    ]
